### `question_083.md`

**Вопрос 083.** Что произойдет, если не указать тип исключения в блоке `except` конструкции `try-except` в Python?

A. Блок `except` пропустит все исключения.
B. Блок `except` перехватит все исключения, независимо от их типа.
C. Программа немедленно завершится с ошибкой.
D. Блок `except` обработает только исключения типа `Exception`.

**Правильный ответ: B**

**Объяснение:**

Если вы не укажете тип исключения в блоке `except`, то он будет действовать как обработчик для всех исключений, которые могут возникнуть в блоке `try`. Это может быть полезно для отлова любых непредвиденных ошибок, но в некоторых ситуациях это может помешать в точной отладке кода, поскольку будет трудно определить тип произошедшей ошибки.

*   **Вариант A** не верен: Блок `except` не пропускает исключения.
*   **Вариант B** верен: Блок `except` без указания типа перехватывает любое исключение.
*   **Вариант C** не верен: Программа не завершится при перехвате исключения.
*   **Вариант D** не верен: Исключения класса `Exception` обрабатываются только, если они указаны явно.

**Пример:**

```python
try:
    x: int = 10 / 0
except: # перехватит любое исключение
    print("Произошла ошибка")

try:
    x: int = int("abc") # вызовет ValueError
except ValueError:
    print("Перехвачено ValueError") # перехватит только ValueError
except: # перехватит любое исключение, кроме ValueError
   print("Произошла ошибка!")
```

**В результате:**

*   В первом примере блок `except` перехватывает исключение `ZeroDivisionError`.
*   Во втором примере, первое `except` перехватывает `ValueError`, а второе `except`  не будет выполняться, так как исключение уже было обработано.

Таким образом, **вариант B** является правильным.
